lection 4 Карточки на главной странице
js-tasks-ru/htmlcss-20220519_n-zbiranik pull request #10
Opened 2022-06-04 09:27 UTC by natkazb

2022-06-04 09:27 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-06-05 18:26 UTC, GSemikozov requested changes

2022-06-05 18:26 UTC, GSemikozov commented on components/card/card.css
> +    width: 350px;
на уровне блока можно разве что flex-basis - через width жестко фиксировать не надо

2022-06-06 09:47 UTC, natkazb commented on components/card/card.css
> +    width: 350px;
поменяла на flex-basis: 350px;
так будет правильно?
ведь у карточек сейчас нет содержимого

2022-06-06 14:27 UTC, GSemikozov commented on components/card/card.css
> +    width: 350px;
да, можно так

2022-06-07 17:58 UTC, GSemikozov requested changes

2022-06-07 17:58 UTC, GSemikozov commented on components/histogram/histogram.css
> +    margin-top: 80px;
марджины на уровне блока (модификатор относится к блоку) не задаем (отступы можно через класс-микс внутри карточки, либо через этот модификатор можно просто ограничить ширину, а в карточке все превью должны выравниваться по середине)

2022-06-09 02:01 UTC, natkazb commented on components/histogram/histogram.css
> +    margin-top: 80px;
исправлено

2022-06-09 02:05 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-06-09 15:33 UTC, GSemikozov approved these changes

2022-06-09 15:33 UTC, merged