lection 5 Страница компонента
js-tasks-ru/htmlcss-20220519_n-zbiranik pull request #11
Opened 2022-06-05 16:06 UTC by natkazb

2022-06-05 16:06 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-06-05 18:27 UTC, GSemikozov requested changes

2022-06-05 18:27 UTC, GSemikozov commented on components/main/main.css
> +    padding: 36px 165px 92px 165px;
вместо паддингов по 165px не забываем использовать .container

2022-06-06 09:07 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-06-06 09:16 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-06-06 09:48 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-06-07 11:03 UTC, natkazb commented on components/main/main.css
> +    padding: 36px 165px 92px 165px;
исправлено

2022-06-07 11:09 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-06-07 11:11 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-06-07 17:58 UTC, GSemikozov approved these changes

2022-06-07 17:58 UTC, merged