lection 7 tabs
js-tasks-ru/htmlcss-20220519_n-zbiranik pull request #17
Opened 2022-06-11 15:43 UTC by natkazb

2022-06-11 15:44 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-06-13 10:47 UTC, GSemikozov requested changes

2022-06-13 10:47 UTC, GSemikozov commented on 07-lection5/05-tabs/tabs.css
> +#all-tab:checked ~ .tabs__scroller label[for="all-tab"]{
у label ведь есть класс )

2022-06-14 08:48 UTC, natkazb commented on 07-lection5/05-tabs/tabs.css
> +#all-tab:checked ~ .tabs__scroller label[for="all-tab"]{
исправлено

2022-06-14 20:18 UTC, GSemikozov approved these changes

2022-06-14 20:18 UTC, merged