task 04 solution for task 1 histogram
js-tasks-ru/htmlcss-20220519_n-zbiranik pull request #6
Opened 2022-05-29 10:37 UTC by natkazb

2022-05-29 10:38 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-05-29 12:14 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-05-29 20:40 UTC, GSemikozov requested changes

2022-05-29 20:40 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    margin: 0;
марджины все равно на уровне блока и так не задаем, можно убрать обнуление)

2022-05-29 20:40 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram header{
.histogram__header

2022-05-29 20:40 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram main{
.histogram__main

2022-05-29 20:40 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    font-style: normal;'
удалить в конце строки `'`

2022-05-29 20:40 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram__detail a{
.histogram__detail a -> .histogram__link

2022-05-29 20:40 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    justify-content: space-between;
лишнее, можно удалить

2022-05-29 20:40 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    margin: 20px 0 0 0;
39

2022-05-29 20:40 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    width: 100%;
не нужно)
здесь как раз важно использовать flex-basis (9px) + flex-grow (1)

2022-05-29 20:40 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__title{
skeleton__title + skeleton__text - один и тот же элемент, можно было бы назвать skeleton__line

2022-05-29 20:40 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__title_first{
first / second - плохие модификаторы, поскольку модификаторы в своем названии должны отображать ЧТО или КАК они модифицируют + привязка порядка следования это плохо, поэтому я бы советовал поменять например на .skeleton__line_small / .skeleton__line_medium и тд

2022-05-30 09:05 UTC, natkazb commented on 04-lection2/01-histogram/histogram.css
> +    margin: 0;
убрала margin: 0;

2022-05-30 09:07 UTC, natkazb commented on 04-lection2/01-histogram/histogram.css
> +.histogram header{
у меня это .histogram__titles пернесла в него стили

2022-05-30 09:08 UTC, natkazb commented on 04-lection2/01-histogram/histogram.css
> +.histogram main{
<main class="histogram__main">
исправила

2022-05-30 09:08 UTC, natkazb commented on 04-lection2/01-histogram/histogram.css
> +    font-style: normal;'
исправлено

2022-05-30 09:11 UTC, natkazb commented on 04-lection2/01-histogram/histogram.css
> +.histogram__detail a{
исправлено

2022-05-30 09:12 UTC, natkazb commented on 04-lection2/01-histogram/histogram.css
> +    justify-content: space-between;
убрала justify-content: space-between;

2022-05-30 09:13 UTC, natkazb commented on 04-lection2/01-histogram/histogram.css
> +    margin: 20px 0 0 0;
margin: 39px 0 0 0;

2022-05-30 09:16 UTC, natkazb commented on 04-lection2/01-histogram/histogram.css
> +    width: 100%;
убрала width: 100%;
поставила
flex-basis: 9px;
flex-grow: 1;

а почему flex-basis именно 9px, тут можно любое значение написать?

2022-05-30 09:18 UTC, natkazb commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__title{
точно, не заметила, исправила!

2022-05-30 09:22 UTC, natkazb commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__title_first{
переименовала

2022-05-30 09:23 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-05-30 15:06 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    width: 100%;
это просто базовая ширина, в макете она 9px )

2022-05-30 15:08 UTC, GSemikozov requested changes

2022-05-30 15:08 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    gap: 1px;
вот здесь лучше зафиксировать высоту как в дизайне на 50px, чтобы колонкам задавать высоту в процентах от 1 до 100 относительно этого значения

2022-05-30 15:11 UTC, natkazb commented on 04-lection2/01-histogram/histogram.css
> +    width: 100%;
а, ясно, спасибо!

2022-05-30 15:37 UTC, natkazb commented on 04-lection2/01-histogram/histogram.css
> +    gap: 1px;
исправлено

2022-05-30 15:38 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-05-30 15:40 UTC, GSemikozov approved these changes

2022-05-30 15:40 UTC, merged