lection 5 solution for task 3 calendar
js-tasks-ru/htmlcss-20220519_n-zbiranik pull request #8
Opened 2022-06-03 06:04 UTC by natkazb

2022-06-03 06:04 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-06-05 18:23 UTC, GSemikozov requested changes

2022-06-05 18:23 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +    min-height: 324px;
лишнее

2022-06-05 18:23 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +    color: #334D6E;
не забываем про переменные)

2022-06-05 18:23 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +    padding-top: 8px;
точно ли надо? вероятно, правильнее задать оступ у title, который может быть опциональным

2022-06-05 18:23 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +.calendar__day{
если в большинстве свойств .calendar__day и .calendar__date дублируются, можно то что дублируется записать через `.calendar__date, .calendar__day {}`

2022-06-06 08:41 UTC, natkazb commented on 05-lection3/03-calendar/calendar.css
> +    min-height: 324px;
убрала

2022-06-06 08:57 UTC, natkazb commented on 05-lection3/03-calendar/calendar.css
> +    color: #334D6E;
перевела все цвета в переменные

2022-06-06 08:59 UTC, natkazb commented on 05-lection3/03-calendar/calendar.css
> +    padding-top: 8px;
перенесла отступ в calendar__title

2022-06-06 09:06 UTC, natkazb commented on 05-lection3/03-calendar/calendar.css
> +.calendar__day{
исправила

2022-06-06 14:26 UTC, GSemikozov approved these changes

2022-06-06 14:26 UTC, merged