lection 5 solution for task 2 modal
js-tasks-ru/htmlcss-20220519_n-zbiranik pull request #9
Opened 2022-06-03 15:49 UTC by natkazb

2022-06-03 15:50 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-06-05 18:25 UTC, GSemikozov requested changes

2022-06-05 18:25 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.modal__background{
лишний элемент, удалим

2022-06-05 18:25 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    display: none;
на уровне блока задаем полу-прозрачный фон через rgba + позиционируем как fixed и растягиваем на 100% ширины и высоты страницы

2022-06-06 09:16 UTC, natkazb commented on 05-lection3/02-modal/modal.css
> +.modal__background{
исправлено, перенесла стили в modal

2022-06-06 09:16 UTC, natkazb commented on 05-lection3/02-modal/modal.css
> +    display: none;
исправлено

2022-06-06 14:27 UTC, GSemikozov approved these changes

2022-06-06 14:27 UTC, merged